
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2022-01-31T17:30:59.184901500 by glen on fullfillment
// 
// a8-versions build/versioning info follows
// 
// 
// 
//      

val appVersion = a8.sbt_a8.versionStamp(file("."))

val scalaLibVersion = "2.12.12"
val model3Version = "2.7.1-20210602_1321_master"

scalacOptions in Global ++= Seq("-deprecation", "-unchecked", "-feature")


publishTo in Global := sonatypePublishToBundle.value
credentials in Global += Credentials(Path.userHome / ".sbt" / "sonatype.credentials")

scalaVersion in Global := scalaLibVersion

organization in Global := "a8"

version in Global := appVersion

versionScheme in Global := Some("strict")

serverConnectionType in Global := ConnectionType.Local


lazy val versions =
  Common
    .jvmProject("a8-versions", file("."), "versions")
    .settings(
      libraryDependencies ++= Seq(
        "ant" % "ant" % "1.6.2" % "compile",
        "io.get-coursier" %% "coursier" % "2.0.0-RC6" % "compile",
        "io.get-coursier" %% "coursier-cache" % "2.0.0-RC6" % "compile",
        "com.softwaremill.sttp" %% "core" % "1.1.11" % "compile",
        "org.scala-lang.modules" %% "scala-xml" % "1.1.0" % "compile",
        "com.geirsson" %% "fastparse" % "1.0.0" % "compile",
        "io.accur8" %% "a8-sync-api" % "1.0.0-20220120_1124_master",
        "com.beachape" %% "enumeratum-play-json" % "1.5.14" % "compile",
        "org.rogach" %% "scallop" % "3.1.2" % "compile",
      )
    )


   
