
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2020-11-11 13:33:37.521 -0600 by raph on ENNS-PC
// 
// a8-versions build/versioning info follows
// 
//        build_java_version : 1.8.0_111
//        build_os : Mac OS X
//        build_machine_ip : 127.0.0.1
//        build_user : flow
//        build_date : Thu Oct 22 11:18:48 EDT 2020
//        version_number : 1.0.0-20201022_1118_master
//        build_machine : Flow-9.local
//        project_name : a8-versions
// 
//      

val scalaLibVersion = "2.12.12"
val model3Version = "2.7.1-20201110_0934_master"

scalacOptions in Global ++= Seq("-deprecation", "-unchecked", "-feature")

resolvers in Global += "a8-repo" at Common.readRepoUrl()

publishTo in Global := Some("a8-repo-releases" at Common.readRepoUrl())

scalaVersion in Global := scalaLibVersion

organization in Global := "a8"

version in Global := a8.sbt_a8.versionStamp(file("."))

serverConnectionType in Global := ConnectionType.Local

bloopAggregateSourceDependencies in Global := true

bloopExportJarClassifiers in Global := Some(Set("sources"))


lazy val versions =
  Common
    .jvmProject("a8-versions", file("."), "versions")
    .settings(
      libraryDependencies ++= Seq(
        "io.get-coursier" %% "coursier" % "2.0.0-RC6" % "compile",
        "io.get-coursier" %% "coursier-cache" % "2.0.0-RC6" % "compile",
        "com.softwaremill.sttp" %% "core" % "1.1.11" % "compile",
        "org.scala-lang.modules" %% "scala-xml" % "1.1.0" % "compile",
        "com.geirsson" %% "fastparse" % "1.0.0" % "compile",
        "a8" %% "m3-common" % model3Version % "compile",
        "a8" %% "m3-impl-api" % model3Version % "compile",
        "com.beachape" %% "enumeratum-play-json" % "1.5.14" % "compile",
        "org.rogach" %% "scallop" % "3.1.2" % "compile",
      )
    )


   
