
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2019-12-04 11:18:23.389 -0600 by raph on ENNS-PC
// 
// a8-versions build/versioning info follows
// 
//        build_java_version : 1.8.0_222
//        build_os : Linux
//        build_machine_ip : 172.31.25.1
//        build_user : raph
//        build_date : Fri Oct 18 18:32:11 EDT 2019
//        version_number : 1.0.0-20191018_1832_master
//        build_machine : basil
//        project_name : a8-versions
// 
//      

addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.28")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")

resolvers += "a8-sbt-plugins" at "https://accur8.jfrog.io/accur8/sbt-plugins/"
credentials += Credentials(Path.userHome / ".sbt" / "credentials")

addSbtPlugin("com.lihaoyi" % "workbench" % "0.4.0")

libraryDependencies += "org.slf4j" % "slf4j-nop" % "1.7.21"
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")

addSbtPlugin("a8" % "sbt-a8" % "1.1.0-20191014_0945")

addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.0.0-M10")
